### ISSUE TITLE
chronological order of extracted audio files

### ISSUE THREAD

**Issue by DD4WH** [mcguirepr89/BirdNET-Pi#37] opened 2021-10-16 08:24 UTC
just a very small "cosmetic issue" :-)

* by default the extracted files under by_common_name come sorted by name and not by date ("Modified") --> because the confidence score is part of the filename, the sorting by name does not exactly match the sorting by date
* I can successfully sort them by clicking on the "Modified" sorting arrow
* However, it would be good to have them sorted by date/Modified as the default setting 

Keep up the good work!

**Comment by mcguirepr89** [comment] 2021-10-16 13:44
As much as I would love to do this for you, I'm afraid that I am not able to help. Caddy creates those file-serving pages itself and defaults with a sorted-by-name approach. While I am able to alter the Caddy's file-serving page for the main birdnetpi.local (since I know exactly which directories it will contain), I'm not able to do any customization to the By Common, By Scientific, nor any other page. The issue is that that index page is very dynamic and is recreated every time its content changes.

It seems that for the foreseeable future you will need to use the "Modified" sorting column for a view that arranges the directories by time. I'll need to close this issue since I don't have any recourse in handling the request -- I'm sorry, but I do appreciate the feedback and would have liked to help.

My best,
Patrick

**Closed by mcguirepr89** 2021-10-16 13:44 UTC
